package com.yumi.cafe.service;
import com.yumi.cafe.dto.*;import com.yumi.cafe.model.*;import com.yumi.cafe.repository.*;import org.springframework.beans.factory.annotation.Value;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import java.math.*;import java.util.*;
@Service public class OrderService {private final MenuItemRepository menu;private final OrderRepository orders;private final BigDecimal fee,threshold,taxRate;public OrderService(MenuItemRepository m,OrderRepository o,@Value("${app.delivery.fee}")BigDecimal f,@Value("${app.free.delivery.threshold}")BigDecimal t,@Value("${app.tax.rate}")BigDecimal tr){menu=m;orders=o;fee=f;threshold=t;taxRate=tr;}
 @Transactional public OrderResponse create(OrderRequest r){if("Delivery".equalsIgnoreCase(r.fulfillmentType())&&(r.address()==null||r.address().isBlank()))throw new IllegalArgumentException("Delivery address is required");Order o=new Order();o.setOrderNumber("YUMI-"+UUID.randomUUID().toString().substring(0,6).toUpperCase());o.setCustomerName(r.customerName().trim());o.setPhone(r.phone());o.setFulfillmentType(r.fulfillmentType());o.setAddress(r.address());o.setPaymentMethod(r.paymentMethod());o.setStatus("RECEIVED");o.setPaymentStatus("Cash".equalsIgnoreCase(r.paymentMethod())?"PENDING":"PENDING");BigDecimal sub=BigDecimal.ZERO;
 for(var req:r.items()){MenuItem m=menu.findById(req.menuItemId()).orElseThrow(()->new IllegalArgumentException("Menu item not found: "+req.menuItemId()));if(!m.isActive())throw new IllegalArgumentException("Menu item unavailable: "+m.getName());String size=req.size()==null?"REGULAR":req.size().toUpperCase();BigDecimal price="MEDIUM".equals(size)?m.getMediumPrice():m.getPrice();if(price==null)throw new IllegalArgumentException("Medium size unavailable for "+m.getName());BigDecimal line=price.multiply(BigDecimal.valueOf(req.quantity()));OrderItem oi=new OrderItem();oi.setMenuItemId(m.getId());oi.setItemName(m.getName());oi.setSize(size);oi.setQuantity(req.quantity());oi.setUnitPrice(price);oi.setLineTotal(line);o.addItem(oi);sub=sub.add(line);}
 BigDecimal tax=sub.multiply(taxRate).setScale(2,RoundingMode.HALF_UP);BigDecimal del="Delivery".equalsIgnoreCase(r.fulfillmentType())?(sub.compareTo(threshold)>=0?BigDecimal.ZERO:fee):BigDecimal.ZERO;o.setSubtotal(sub);o.setTax(tax);o.setDeliveryFee(del);o.setTotal(sub.add(tax).add(del));orders.save(o);return response(o);}
 @Transactional public OrderResponse updateStatus(String number,String status){Order o=orders.findByOrderNumber(number).orElseThrow();o.setStatus(status.toUpperCase());return response(o);} @Transactional public void markPaid(String number){Order o=orders.findByOrderNumber(number).orElseThrow();o.setPaymentStatus("PAID");}
 public List<OrderResponse> all(){return orders.findTop100ByOrderByCreatedAtDesc().stream().map(this::response).toList();}
 private OrderResponse response(Order o){return new OrderResponse(o.getOrderNumber(),o.getSubtotal(),o.getTax(),o.getDeliveryFee(),o.getTotal(),o.getStatus(),o.getPaymentStatus(),o.getItems().stream().map(i->new OrderResponse.Item(i.getItemName(),i.getSize(),i.getQuantity(),i.getUnitPrice(),i.getLineTotal())).toList());}}
