import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { ArrowRight, Check, ChevronRight, Clock3, MapPin, Minus, Plus, Search, ShoppingBag, Sparkles, Truck, X } from 'lucide-react';
import './styles.css';

const MENU = [
 {id:'tea',name:'Tea',icon:'🍵',items:[['Regular Tea',15],['Masala Tea',20],['Ginger Tea',20],['Lemon Tea',20]]},
 {id:'hot-coffee',name:'Hot Coffee',icon:'☕',items:[['Regular Coffee',20],['Espresso',40],['Americano',50],['Cappuccino',60],['Cafe Latte',70]]},
 {id:'cold-coffee',name:'Cold Coffee',icon:'🧋',items:[['Cold Coffee',69],['Chocolate Cold Coffee',79]]},
 {id:'shakes',name:'Shakes',icon:'🥤',items:[['Vanilla Shake',59],['Chocolate Shake',69],['Strawberry Shake',69],['Banana Shake',59],['Oreo Shake',79],['KitKat Shake',89],['Cold Coffee',69],['Chocolate Cold Coffee',79],['YUMI Special Shake',99]]},
 {id:'mocktails',name:'Mocktails',icon:'🍹',items:[['Lemon Mint',49],['Virgin Mojito',59],['Blue Lagoon',59],['Green Apple Mojito',59],['Watermelon Mojito',59],['Strawberry Mojito',69],['Lemon Soda',39],['YUMI Special Mocktail',79]]},
 {id:'patties',name:'Patties',icon:'🥐',items:[['Veg Patties',25],['Masala Patties',30],['Paneer Patties',35],['Tandoori Paneer Patties',40],['Cheese Patties',40],['Cheese Corn Patties',40],['YUMI Special Patties',45]]},
 {id:'sandwich',name:'Sandwich',icon:'🥪',items:[['Veg Sandwich',49],['Veg Grilled Sandwich',59],['Cheese Sandwich',69],['Cheese Corn Sandwich',79],['Paneer Sandwich',79],['Tandoori Paneer Sandwich',89],['YUMI Special Sandwich',99]]},
 {id:'burger',name:'Burger',icon:'🍔',items:[['Veg Burger',49],['Cheese Burger',69],['Paneer Burger',79],['Cheese Paneer Burger',89],['Tandoori Paneer Burger',89],['YUMI Special Burger',99]]},
 {id:'wraps',name:'Wraps',icon:'🌯',items:[['Veg Wrap',49],['Cheese Veg Wrap',59],['Paneer Wrap',59],['Tandoori Paneer Wrap',79],['Cheese Paneer Wrap',89],['YUMI Special Wrap',99]]},
 {id:'momos',name:'Momos',icon:'🥟',items:[['Veg Steamed Momos',59],['Veg Fried Momos',69],['Paneer Momos',79],['Cheese Momos',89],['Kurkure Momos',99],['YUMI Special Momos',109]]},
 {id:'fries',name:'Fries',icon:'🍟',items:[['French Fries',79],['YUMI Special Long Fries',99]]},
 {id:'maggi',name:'Maggi',icon:'🍝',items:[['Masala Maggi',59],['Veg Maggi',59],['Cheese Maggi',79],['Paneer Maggi',79],['YUMI Special Maggi',99]]},
 {id:'pav-bhaji',name:'Pav Bhaji',icon:'🍞',items:[['Classic Pav Bhaji',79],['Cheese Pav Bhaji',99],['YUMI Special Pav Bhaji',119]]},
 {id:'garlic-bread',name:'Garlic Bread',icon:'🥖',items:[['Garlic Bread',79],['Cheese Garlic Bread',99],['YUMI Special Garlic Bread',119]]},
 {id:'pasta',name:'Pasta',icon:'🍝',items:[['Red Sauce Pasta',99],['White Sauce Pasta',109],['Pink Sauce Pasta',119]]},
 {id:'pizza',name:'Pizza',icon:'🍕',note:'7” Regular · 9” Medium',sizes:true,items:[['Margherita Pizza',89,129],['Veggie Pizza',109,149],['Cheese Corn Pizza',119,159],['Paneer Pizza',129,169],['Tandoori Paneer Pizza',149,189],['Cheese Paneer Pizza',159,199],['YUMI Special Pizza',179,229]]},
 {id:'manchurian',name:'Manchurian',icon:'🥢',items:[['Veg Manchurian Dry',89],['Veg Manchurian Gravy',89],['Paneer Manchurian',119],['Cheese Manchurian',119],['Paneer Manchurian Gravy',119],['YUMI Special Manchurian',139]]},
 {id:'chilli',name:'Chilli Specials',icon:'🌶️',items:[['Chilli Potato',79],['Honey Chilli Potato',89],['Chilli Paneer Dry',119],['Chilli Paneer Gravy',129],['YUMI Special Chilli Paneer',149]]},
 {id:'pastries',name:'Pastries',icon:'🍰',items:[['Fresh Cream Pastry',20],['Vanilla Pastry',25],['Pineapple Pastry',25],['Chocolate Pastry',25],['Black Forest Pastry',35],['Red Velvet Pastry',40]]},
 {id:'cupcakes',name:'Cupcakes',icon:'🧁',items:[['Vanilla Cupcake',25],['Chocolate Cupcake',30],['Red Velvet Cupcake',40]]}
];

const SECTIONS = [
 {id:'sip',eyebrow:'START WITH A SIP',title:'Tea, coffee & cool sips.',ids:['tea','hot-coffee','cold-coffee','shakes','mocktails']},
 {id:'cafe',eyebrow:'CAFE FAVOURITES',title:'Easy bites, made for sharing.',ids:['patties','sandwich','burger','wraps','momos','fries','maggi','pav-bhaji','garlic-bread','pasta']},
 {id:'mains',eyebrow:'FROM THE KITCHEN',title:'The hearty YUMI favourites.',ids:['pizza','manchurian','chilli']},
 {id:'bakery',eyebrow:'BAKERY & SWEET',title:'A little sweeter to finish.',ids:['pastries','cupcakes']}
];
const TAX_RATE = 0.05; // Demo UI rate; configure actual applicable GST/tax in production.
const money = n => `₹${Number(n || 0).toLocaleString('en-IN')}`;
const STORAGE='yumi-cart-v3';

function App(){
 const [catalog,setCatalog]=useState(MENU);
 const [active,setActive]=useState('all'),[query,setQuery]=useState(''),[cart,setCart]=useState(()=>{try{return JSON.parse(localStorage.getItem(STORAGE)||'[]')}catch{return[]}}),[drawer,setDrawer]=useState(false),[checkout,setCheckout]=useState(false),[payment,setPayment]=useState(false),[success,setSuccess]=useState(null),[toast,setToast]=useState(''),[paymentMethod,setPaymentMethod]=useState('UPI');
 const [customer,setCustomer]=useState({name:'',phone:'',type:'Pickup',address:''});
 useEffect(()=>localStorage.setItem(STORAGE,JSON.stringify(cart)),[cart]);
 useEffect(()=>{fetch('/api/menu').then(r=>r.ok?r.json():Promise.reject()).then(rows=>{const groups={};rows.forEach(m=>{groups[m.category]??={id:m.category.toLowerCase().replaceAll(' ','-'),name:m.category,icon:MENU.find(x=>x.name===m.category)?.icon||'🍽️',items:[],sizes:m.category==='Pizza',note:m.category==='Pizza'?'7” Regular · 9” Medium':undefined};groups[m.category].items.push([m.name,Number(m.price),m.mediumPrice==null?null:Number(m.mediumPrice),m.id]);});setCatalog(Object.values(groups))}).catch(()=>{});},[]);
 const catalogMap=useMemo(()=>Object.fromEntries(catalog.map(g=>[g.id,g])),[catalog]);
 const matches=(g)=>g.items.some(x=>x[0].toLowerCase().includes(query.trim().toLowerCase()));
 const filteredSections=useMemo(()=>SECTIONS.map(s=>({...s,groups:s.ids.map(id=>catalogMap[id]).filter(Boolean).map(g=>({...g,items:g.items.filter(x=>x[0].toLowerCase().includes(query.trim().toLowerCase()))})).filter(g=>matches(g))})).filter(s=>s.groups.length),[catalogMap,query]);
 const filteredByActive=useMemo(()=>active==='all'?filteredSections:filteredSections.map(s=>({...s,groups:s.groups.filter(g=>g.id===active)})).filter(s=>s.groups.length),[active,filteredSections]);
 const count=cart.reduce((s,x)=>s+x.qty,0),subtotal=cart.reduce((s,x)=>s+x.price*x.qty,0),tax=Number((subtotal*TAX_RATE).toFixed(2)),delivery=customer.type==='Delivery'?(subtotal>=299?0:30):0,total=subtotal+tax+delivery;
 const notify=t=>{setToast(t);setTimeout(()=>setToast(''),1600)};
 const keyFor=(group,item,size)=>`${group.id}-${size?`${item[0]}-${size}`:item[0]}`;
 const cartQty=(group,item,size)=>cart.find(x=>x.key===keyFor(group,item,size))?.qty||0;
 const add=(group,item,size)=>{const price=size==='medium'?item[2]:item[1],name=size?`${item[0]} · ${size==='medium'?'Medium':'Regular'}`:item[0],key=keyFor(group,item,size);setCart(c=>{const f=c.find(x=>x.key===key);return f?c.map(x=>x.key===key?{...x,qty:x.qty+1}:x):[...c,{key,name,price,qty:1,category:group.name,menuItemId:item[3]??null,size:size?size.toUpperCase():'REGULAR'}]});notify(`${name} added`)};
 const qty=(key,d)=>setCart(c=>c.map(x=>x.key===key?{...x,qty:x.qty+d}:x).filter(x=>x.qty>0));
 const continueCheckout=e=>{e.preventDefault();if(!customer.name.trim()||!/^[6-9]\d{9}$/.test(customer.phone)){notify('Enter a valid Indian mobile number');return}if(customer.type==='Delivery'&&!customer.address.trim()){notify('Please add your delivery address');return}setCheckout(false);setPayment(true)};
 const place=async()=>{const fallback={id:`YUMI-${Date.now().toString().slice(-6)}`,total,customer,...customer,items:cart,payment:paymentMethod,createdAt:new Date().toISOString()};try{const r=await fetch('/api/orders',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({customerName:customer.name,phone:customer.phone,fulfillmentType:customer.type,address:customer.address,paymentMethod,items:cart.map(x=>({menuItemId:x.menuItemId,quantity:x.qty,size:x.size}))})});if(!r.ok)throw new Error('order');const data=await r.json();setSuccess({...fallback,id:data.orderNumber,total:Number(data.total)});}catch{setSuccess(fallback)}setCart([]);setPayment(false)};
 const scrollMenu=()=>document.getElementById('menu').scrollIntoView({behavior:'smooth',block:'start'});
 return <div className="app">
  <header className="nav">
   <button className="brand" onClick={()=>window.scrollTo({top:0,behavior:'smooth'})} aria-label="YUMI home"><img src="/logo-yumi.png" alt="YUMI Bakery & Cafe"/><span><b>YUMI</b><small>Bakery & Cafe</small></span></button>
   <div className="nav-tag"><span>Fresh</span><i>·</i><span>Tasty</span><i>·</i><span>Made with Love</span></div>
   <button className="cart-pill" onClick={()=>setDrawer(true)}><ShoppingBag size={18}/><span>Basket</span>{count>0&&<b>{count}</b>}</button>
  </header>
  <main>
   <section className="hero">
    <div className="hero-copy"><span className="eyebrow">YUMI · BAKERY & CAFE</span><h1>Good food.<br/><i>Brighter days.</i></h1><p>From your first cup of tea to a fresh pastry at the end — simple food, warm moments, made with love.</p><div className="hero-row"><button className="btn primary" onClick={scrollMenu}>Explore menu <ArrowRight size={17}/></button><div className="location"><MapPin size={15}/><span>Ratangarh & around 10 km</span><small>Pre-order & delivery available</small></div></div></div>
    <div className="hero-visual"><div className="hero-orbit orbit-one"/><div className="hero-orbit orbit-two"/><div className="hero-logo-card"><img src="/logo-yumi.png" alt="YUMI"/></div><div className="floating-note note-one"><span>☕</span><b>Start with a sip</b><small>Tea · Coffee · Shakes</small></div><div className="floating-note note-two"><Sparkles size={14}/><b>Freshly prepared</b><small>Made to order</small></div></div>
   </section>
   <section className="quick"><div><Clock3 size={19}/><span><b>Freshly prepared</b><small>Made to order</small></span></div><div><Truck size={19}/><span><b>Delivery available</b><small>Within ~10 km</small></span></div><div><Sparkles size={19}/><span><b>Vegetarian menu</b><small>Something for everyone</small></span></div></section>
   <section className="menu" id="menu">
    <div className="section-title"><div><span className="eyebrow">THE YUMI MENU</span><h2>Take your time.<br/><i>Find your favourite.</i></h2></div><label className="search"><Search size={21}/><input aria-label="Search dishes" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search dishes, drinks & desserts..."/></label></div>
    <div className="chips"><button className={active==='all'?'on':''} onClick={()=>setActive('all')}>All</button>{MENU.map(g=><button className={active===g.id?'on':''} key={g.id} onClick={()=>setActive(g.id)}>{g.name}</button>)}</div>
    {filteredByActive.map(section=><section className="menu-section" key={section.id}><div className="menu-section-heading"><span>{section.eyebrow}</span><h3>{section.title}</h3></div><div className="menu-grid">{section.groups.map(g=><article className="card" key={g.id}><div className="card-head"><span>{g.icon}</span><div><h4>{g.name}</h4>{g.note&&<small>{g.note}</small>}</div></div><div className="items">{g.items.map(item=>{const regQty=cartQty(g,item,'regular'),medQty=cartQty(g,item,'medium'),normalQty=cartQty(g,item);return <div className="item" key={item[0]}><div className="item-name"><b>{item[0]}</b></div>{g.sizes?<div className="price-group"><ItemControl qty={regQty} price={item[1]} label="Reg" onAdd={()=>add(g,item,'regular')} onMinus={()=>qty(keyFor(g,item,'regular'),-1)} onPlus={()=>qty(keyFor(g,item,'regular'),1)}/><ItemControl qty={medQty} price={item[2]} label="Med" onAdd={()=>add(g,item,'medium')} onMinus={()=>qty(keyFor(g,item,'medium'),-1)} onPlus={()=>qty(keyFor(g,item,'medium'),1)}/></div>:<ItemControl qty={normalQty} price={item[1]} onAdd={()=>add(g,item)} onMinus={()=>qty(keyFor(g,item),-1)} onPlus={()=>qty(keyFor(g,item),1)}/>}</div>})}</div></article>)}</div></section>)}
    {!filteredByActive.length&&<div className="empty"><Search size={28}/><h3>No dish found</h3><p>Try another name or browse all categories.</p><button className="btn ghost" onClick={()=>{setQuery('');setActive('all')}}>Show full menu</button></div>}
   </section>
  </main>
  <footer><div className="footer-brand"><img src="/logo-yumi.png" alt="YUMI"/><span><b>YUMI</b><small>Bakery & Cafe</small></span></div><div>Eat · Drink · Be Happy</div><div>Ratangarh · Pre-order & delivery available</div></footer>
  {count>0&&<button className="bottom-cart" onClick={()=>setDrawer(true)}><span className="bottom-cart-count">{count}</span><span><b>View basket</b><small>{count} {count===1?'item':'items'} · {money(total)}</small></span><span className="bottom-cart-arrow"><ChevronRight size={19}/></span></button>}
  {drawer&&<div className="backdrop" onClick={()=>setDrawer(false)}><aside className="drawer" onClick={e=>e.stopPropagation()}><div className="modal-head"><div><span className="eyebrow">YOUR ORDER</span><h2>Your basket</h2></div><button className="close" onClick={()=>setDrawer(false)}><X/></button></div>{cart.length?<><div className="cart-list">{cart.map(x=><div className="cart-line" key={x.key}><div className="cart-info"><b>{x.name}</b><small>{money(x.price)} each</small></div><div className="counter"><button onClick={()=>qty(x.key,-1)}><Minus/></button><b>{x.qty}</b><button onClick={()=>qty(x.key,1)}><Plus/></button></div><strong>{money(x.price*x.qty)}</strong></div>)}</div><div className="bill"><div><span>Subtotal</span><b>{money(subtotal)}</b></div><div><span>Taxes (5% demo)</span><b>{money(tax)}</b></div>{customer.type==='Delivery'&&<div><span>Delivery</span><b>{delivery?money(delivery):'FREE'}</b></div>}<div className="grand"><span>Total</span><b>{money(total)}</b></div><button className="btn primary wide" onClick={()=>{setDrawer(false);setCheckout(true)}}>Continue to checkout <ChevronRight size={17}/></button></div></>:<div className="empty-cart"><ShoppingBag size={42}/><h3>Your basket is empty</h3><p>Add something delicious from the menu.</p><button className="btn ghost" onClick={()=>setDrawer(false)}>Back to menu</button></div>}</aside></div>}
  {checkout&&<div className="modal-backdrop"><div className="modal"><div className="modal-head"><div><span className="eyebrow">CHECKOUT</span><h2>Almost there.</h2></div><button className="close" onClick={()=>setCheckout(false)}><X/></button></div><form onSubmit={continueCheckout}><label>Name<input value={customer.name} onChange={e=>setCustomer({...customer,name:e.target.value})} placeholder="Your name" autoComplete="name"/></label><label>Mobile number<input value={customer.phone} onChange={e=>setCustomer({...customer,phone:e.target.value.replace(/\D/g,'').slice(0,10)})} placeholder="10-digit mobile number" inputMode="numeric" autoComplete="tel"/></label><div className="seg"><button type="button" className={customer.type==='Pickup'?'selected':''} onClick={()=>setCustomer({...customer,type:'Pickup'})}>🏠 Pickup</button><button type="button" className={customer.type==='Delivery'?'selected':''} onClick={()=>setCustomer({...customer,type:'Delivery'})}>🛵 Delivery</button></div>{customer.type==='Delivery'&&<label>Delivery address<textarea value={customer.address} onChange={e=>setCustomer({...customer,address:e.target.value})} placeholder="House / shop, street, landmark" rows="3"/></label>}<div className="checkout-breakdown"><div><span>Subtotal</span><b>{money(subtotal)}</b></div><div><span>Taxes</span><b>{money(tax)}</b></div>{customer.type==='Delivery'&&<div><span>Delivery</span><b>{delivery?money(delivery):'FREE'}</b></div>}</div><div className="total-row"><span>Payable</span><b>{money(total)}</b></div><button className="btn primary wide" type="submit">Continue to payment <ArrowRight size={16}/></button></form></div></div>}
  {payment&&<div className="modal-backdrop"><div className="modal"><div className="modal-head"><div><span className="eyebrow">SECURE CHECKOUT</span><h2>Choose payment.</h2></div><button className="close" onClick={()=>setPayment(false)}><X/></button></div><div className="payment-total"><span>Order total</span><b>{money(total)}</b></div><div className="payment-options">{[['UPI','GPay · PhonePe · Paytm · any UPI app','◉'],['Card','Credit or debit card','▣'],['Cash','Pay at counter / delivery','₹']].map(([name,desc,icon])=><button className={paymentMethod===name?'pay selected':'pay'} key={name} onClick={()=>setPaymentMethod(name)}><span>{icon}</span><div><b>{name}</b><small>{desc}</small></div><ChevronRight size={17}/></button>)}</div>{paymentMethod==='UPI'&&<div className="payment-info"><div className="fake-qr">▦</div><div><b>UPI payment</b><p>Production mode will open your configured payment gateway.</p></div></div>}<button className="btn primary wide" onClick={place}>{paymentMethod==='Cash'?'Place order':'Pay'} {money(total)} <ArrowRight size={16}/></button><small className="secure">🔒 Payment is verified server-side in production</small></div></div>}
  {success&&<div className="modal-backdrop"><div className="success"><div className="success-mark"><Check/></div><span className="eyebrow">ORDER RECEIVED</span><h2>Thank you, {success.customer.name}!</h2><p>Your order <b>#{success.id}</b> has been received.</p><div className="order-summary"><span>Total</span><b>{money(success.total)}</b></div><div className="success-note"><MapPin size={16}/><span>YUMI Bakery & Cafe<br/><small>{success.type==='Delivery'?'We’ll prepare and deliver your order.':'We’ll have your order ready for pickup.'}</small></span></div><button className="btn primary wide" onClick={()=>setSuccess(null)}>Back to menu</button></div></div>}
  {toast&&<div className="toast"><Check size={15}/>{toast}</div>}
 </div>
}

function ItemControl({qty,price,label,onAdd,onMinus,onPlus}){
 return qty>0 ? <div className="item-control"><button aria-label="Decrease quantity" onClick={onMinus}><Minus size={13}/></button><span><b>{money(price)}</b>{label&&<small>{label}</small>}<em>×{qty}</em></span><button aria-label="Increase quantity" onClick={onPlus}><Plus size={13}/></button></div> : <button className="add" onClick={onAdd}><span>{money(price)}</span><Plus size={15}/></button>;
}
createRoot(document.getElementById('root')).render(<App/>);
